name: Погода на GitHub Actions

on:
  push:
    branches:
      - main

jobs:
  weather:
    runs-on: ubuntu-latest

    steps:
    - name: Установка зависимостей
      run: pip install requests
      
    - name: Получение погоды
      run: |
        python_script.py
